FROM php:8.1.9-apache

WORKDIR /var/www/html

# update
RUN docker-php-ext-install pdo pdo_mysql opcache;

RUN a2enmod rewrite && service apache2 restart

# Expose port 80 to the outside world
EXPOSE 80