FROM php:8.1.9-apache

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/conf.d/php.ini"
COPY opcache.ini "$PHP_INI_DIR/conf.d/opcache.ini"

WORKDIR /var/www/html

# update
RUN docker-php-ext-install pdo pdo_mysql opcache;

RUN a2enmod rewrite && service apache2 restart

# Expose port 80 to the outside world
EXPOSE 80